hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "2d4f0b19fe575fb5c7040e152947b5529b2dacf00edb3723ed31bf6ce2600d16"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/ambientsounds-client.json"
hash = "44f5a16487a7583f2561bdd6f0df1bd1755410d75c304356f009229d8a804551"

[[files]]
file = "config/yosbr/config/bebooks/config.properties"
hash = "aff18c28c913dfd09cd926ec3beb2f5a0c64142f504d87b8f3e28f4199f57310"

[[files]]
file = "config/yosbr/config/betteranimationscollection-client.toml"
hash = "7db93548fd24d84dafa32899b419e2ac49c8615a48c2ec9f85a1123fa913d9ae"

[[files]]
file = "config/yosbr/config/blur.json"
hash = "15fb6b0bb80bde573b4d14b4289f7e7682d0a581fb9aff105b03a9d0f24b7661"

[[files]]
file = "config/yosbr/config/brb.toml"
hash = "4a7be5e983a6645e77b20a993596c69d5ca9457320fc2f48de8c01e4a46456d0"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "ae7c0312f352053f4a8208e00bac049061e8654d5db20ec41ce58dcaf9854412"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/chat_heads.json5"
hash = "9edcc54e9287bc9374fe332d1884ef114ce08ef37dfac29803d9116f3d425315"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "fa1de7120195fe5f492cada2cca323e987162dfbac561db666231dea0fa9ca94"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3cb64e81d0abd9d5ce4ef2df7ac254544bf46083e2f19dc1729aa88fc33add00"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "2faf95aad74800a1387edf30a0d7b2c949a38f812ddfb141adba44869569ea17"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "8eb65eef0fd09da262c6b2537e973ae25c7043dbf47169972f0fc7491229d777"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "00a53f09c4d05153c34593562c95bcb65fba831d85ce7b98226b37be419e8673"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "56f694a9f0c31bb096d7d49c0d46cd20554da057f875ed435b3a3c39aba4ff48"

[[files]]
file = "config/yosbr/config/skinlayers.json"
hash = "d13eaaacedf39f6de597127f9dcc7906ee1981dd008d3a68d3d94715558c0db1"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/timeless.json"
hash = "22b9d5fe48d484d4a19c6fcf6f66435024cd0df43b2b808b859526496f2db946"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "c47ea3554cf51890f76152c3cc5ab2ae86a4c81831456cf1e451ee4c581331df"

[[files]]
file = "config/yosbr/options.txt"
hash = "65274fab202c6c21127e8c912669087dc2d1ea514b3fd44893e1b22e6706cc6b"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "9bd6ba58d937a371fc6bb73947e19c75020af78fc16a4a56683e5f289075bb29"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "5fab6c1cc1beb19db884f921897d336934c56793f5f8b84fd9350c1b51d32c8c"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "318519c3574871766c6dc32c0748a899d3b928666d1ed94bf0861ec90507cac0"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "848c49f2ead5e1e71d7be95d2d9e1cb992631faf91500b9c59e72d61afca33fd"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "385f6606afc7086a39eaceec2df95e0c2c5d7aa3a3b31cb67e2a337eb10a4167"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "71eb1aaabf8edb4cbf06083dbcb88d2753f784c02210783f4292175c44df1dd9"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "d8a788b59e239573694e09a72c14dff19cffdd5b85671fd6722130d7f4f0e831"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "1de0c1c60ce9fbc03b06457b12c490406fc48d2b79dda58528dbad081ae9a466"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "c62ded87bfe165a691ab2845149b09788d9a0cb308e44ee7ee6507c846e9bdb3"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "20d7b9a3333ef86d70c3b3becaeccc9ef5961c41e8cd936bb1df9cf0b946c546"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "a8b8e89a322aae5f20d15a3aa21cd5f47e14853f36b9303e3ef0fa717660115a"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "03041cf87decf6ccd51815a2f454d7c0483314e813f3583745433b983103bc42"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "4f37da86319d0c1a5f3f222d30b23798ac1e07ae773caf91f0a8b1f89577fc3f"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "389323d30065bef4d9eb2d965ce19e510bf7c9ffc64f21b6e122f2d95e1cf207"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "847dce2251028733f139692907e89466896dc6ca35cfcc1bdaa0ec1f02aebefb"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9a386c47e3ee11b91e443d8ec1b6084eb0266b5ddbd127ea3e90c7fa4ff5d9fd"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "e663f7a8af3dc2e071bce60131381a2ef243d9cc84ed5b74b1c2ae5cd244ac86"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "6c94f2d5e791983e7cd4d7f2deb3e0abe1d8531ff42843aab1f7e4d8505a44d4"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "5ac6fe9a921d8fa00456ec2e18da02ede5c0da424c5c5b57da1206feeac40ff6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7af4476d6dee900025bd949e921bceeed2166137798e397c06f21a7e2ff26bbe"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "4c5ec7476521092a74d8ae1b894e44903a3d7834898674294f0ce4ddb040b251"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12fe61275734cf8d2554d5f92af20ccb22479118b36a9a56a275ad3f4b1e13fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "36587a2be418f365faa1a6deac5eadcc00b6a79ebacab25ad87839f9ddc021e7"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "12d014178cac4930a88909d241bf537c3908ff9c2c6176f2c8a22a109a4c2363"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/fluidvoidfading.pw.toml"
hash = "27de69cebf60cfe622dbb27d081a4d906067c2c85e5e3c01bcde94cf1232fbc0"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "af10334d5cb965e4255f864d8fe2c3bad90e571492bf61fd84fb55c9a9506d59"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "88a22df96806e32bfd1f80fbd4a94a885148d2372efa5a36c1e8635f06213780"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5d6f1406628a792f100454fb8cbf3ad70a76fe58e0bdb09df3cf5e8d86e878a7"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "5f694b0c16bfbf69b05cb28eef7a553ae548e623bc2cbccc98e01d950d3611db"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "725bcddab89e28a43bc798af763ce2844858ebfccae4e78f2d60dd6ba6194f91"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "fd344aa2c329dbb6b894ac1fcda5e82e1a965967a3dd7493b7a3e0a6eccc2226"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "58b90c52266f89c339a35bd46378d8059d56949d5926c7b25da98719d0b38065"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "cb6164e3c3e40045becd5a12ffda6f4ce1492019add565d49656f15eb7863707"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "a874985359eaa4317b3242136fe65b86207a6d5ab55e0b4aa8f37b90727f0487"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "86f9ed94ae55d745178d1b40991b20f590241e0df353c405d6dfe463e85303da"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "4aef3c4dbc01c945f4a30f63c03607aad77d16ab194983510c10ce516312e258"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "455d878986138a7cebcf3def9d5a4ea34f8b94beee32fac462569cfa16e857ef"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "c3c0af49a34f2ea66faaf78b08f9b8858bbac60d5aca3b85542d45697bb53e36"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9445550cf3fcfaaa145d60528e01c55d2fa798bcfc1232c141ddf3b94b6e0022"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "c9f156a56c3647f8003cc76e36accacf12406be6febeb35341e6f7df7a8dcaaa"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "98255e1e858a1f226fcd3587a962ce7c78112a1f5139d38348f53b74c905de58"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "73721942388d987a53498ea17d5a80637ed4f3863f4ff2f2e546eb3d897f0c64"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "f599da7c46d2acdca321efcf35d78c53d69a73168e86344971b857bc2c754932"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/repeater-sound.pw.toml"
hash = "7a5431a4a93c8aadb13055f131494344163ed51aa61a01f75fe5d40b28903eb0"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "4bdb139f7f4329e080df6b9467c73391652dd85665a6a37dbce799f08baaa219"
metafile = true

[[files]]
file = "mods/screenshot-viewer.pw.toml"
hash = "3ffd98bad6bf131ed40e07b51da46f8b5692982de63ad05cc8c4738e1d7a88ec"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "5c4d91b12d98ab2114129d24500254c0d6e6df3bab66af21367d09a4cfbdf9e5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "6a9b663f2cd6c3f6f35ee30831a8e577aacc27b1851688d2179c9a20b19bde92"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "9779ab4f3a2f5a31a5546e17492167ae1f46426875583f5eb6c4b4e893557d2a"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "ef09549b50c6d26e7796f9019c7af46bf0b90fd89362286325030194373ada82"
metafile = true

[[files]]
file = "mods/timeless.pw.toml"
hash = "fc13937bee0f98cefbfbc2795438fc2c67d0fad23fbeceb12caedf147a34984e"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "146dbdc9a45f945693a356510b0ce7ef670ab1bbd73e7fe461cef41f33519c3c"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dc66d444a8cfd427c3c05d47babcc43f7fca842c1d7731116bd07c7d88441edc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/chat+.pw.toml"
hash = "c02363de4ce87adbeefef2754cc1a38c37920631769d713b700c3c759d0e4fa6"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "9c2f16ea4925e7e8ed263b1f0fc4b5bd159fa72ea8ca246d026bff60e2607c9f"
metafile = true

[[files]]
file = "resourcepacks/enhanced-faithcraft.pw.toml"
hash = "f7ebff83d26ce02fa914ad1546674e534b982c068d8b596ae5393bbcaed9db43"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "3e8b5309e27392a7d965612ef85f47b0507bdacedf3882e3490f9a66188579a5"
metafile = true

[[files]]
file = "resourcepacks/food-tooltips.pw.toml"
hash = "8efd9a6f5ecab8a1329b6b0e4c6512dab34a11df09065a730a199346fe7a28e0"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "2840900657d1be39ec31d5f7bedba2fe4549fda3235bfaceab61243d3c1bdfd0"
metafile = true

[[files]]
file = "shaderpacks/MakeUp-UltraFast-9.3d.txt"
hash = "693ad3426a9baac855c1e1bbc514eccec70cb8f197dac0132b109df85ef537b4"

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "98146b3c9311635f180bfd250781986b88516f930ee652fcbd234788b64ba3b6"
metafile = true
