hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "2d4f0b19fe575fb5c7040e152947b5529b2dacf00edb3723ed31bf6ce2600d16"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/ambientsounds-client.json"
hash = "44f5a16487a7583f2561bdd6f0df1bd1755410d75c304356f009229d8a804551"

[[files]]
file = "config/yosbr/config/bebooks/config.properties"
hash = "aff18c28c913dfd09cd926ec3beb2f5a0c64142f504d87b8f3e28f4199f57310"

[[files]]
file = "config/yosbr/config/betteranimationscollection-client.toml"
hash = "7db93548fd24d84dafa32899b419e2ac49c8615a48c2ec9f85a1123fa913d9ae"

[[files]]
file = "config/yosbr/config/blur.json"
hash = "15fb6b0bb80bde573b4d14b4289f7e7682d0a581fb9aff105b03a9d0f24b7661"

[[files]]
file = "config/yosbr/config/brb.toml"
hash = "4a7be5e983a6645e77b20a993596c69d5ca9457320fc2f48de8c01e4a46456d0"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "ae7c0312f352053f4a8208e00bac049061e8654d5db20ec41ce58dcaf9854412"

[[files]]
file = "config/yosbr/config/cem.conf"
hash = "51519ddcc6823cbe1f22b8977fe103eb8c01b1872899634ddc06814f3ef2da9b"

[[files]]
file = "config/yosbr/config/chat_heads.json5"
hash = "9edcc54e9287bc9374fe332d1884ef114ce08ef37dfac29803d9116f3d425315"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "70785772d8e66e1b75fa58ef0ceff1b598a78a025b05908ffd03c66cb6a1216d"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f6dfdf1384830fbd124bf842bf6e86a4fccfeddbe1ace51f3b7e4bac17e946b9"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "c1a3ccc45a724d291dbd6e8ec5a61baf144590f05630e3223f3228e97ae10a7b"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "0acbe584142db5bf238f533688b7cd7730b74990f29e248a6a32601e096ab331"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "8eb65eef0fd09da262c6b2537e973ae25c7043dbf47169972f0fc7491229d777"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "00a53f09c4d05153c34593562c95bcb65fba831d85ce7b98226b37be419e8673"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "56f694a9f0c31bb096d7d49c0d46cd20554da057f875ed435b3a3c39aba4ff48"

[[files]]
file = "config/yosbr/config/skinlayers.json"
hash = "d13eaaacedf39f6de597127f9dcc7906ee1981dd008d3a68d3d94715558c0db1"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/timeless.json"
hash = "22b9d5fe48d484d4a19c6fcf6f66435024cd0df43b2b808b859526496f2db946"

[[files]]
file = "config/yosbr/config/zoomify.json"
hash = "c47ea3554cf51890f76152c3cc5ab2ae86a4c81831456cf1e451ee4c581331df"

[[files]]
file = "config/yosbr/options.txt"
hash = "65274fab202c6c21127e8c912669087dc2d1ea514b3fd44893e1b22e6706cc6b"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "eb5153b1e4739033f8a5521e83862dffb52e8e33cd9e3532e67dad04b371d440"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "ed903d0b2e147daecbe0ab26174685d0179cd587fcf533e55aa30886eda480b0"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "7749a788cd34e08e2280dc5e05db1bbf375d7a184d787f682f7df19709a754e3"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "385f6606afc7086a39eaceec2df95e0c2c5d7aa3a3b31cb67e2a337eb10a4167"
metafile = true

[[files]]
file = "mods/bettercommandblockui.pw.toml"
hash = "efe9b34407e122ab02444ed4da6820984d2f015fbe2b64242f74bbce35f145d4"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "d8a788b59e239573694e09a72c14dff19cffdd5b85671fd6722130d7f4f0e831"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "1de0c1c60ce9fbc03b06457b12c490406fc48d2b79dda58528dbad081ae9a466"
metafile = true

[[files]]
file = "mods/blur-plus.pw.toml"
hash = "c62ded87bfe165a691ab2845149b09788d9a0cb308e44ee7ee6507c846e9bdb3"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "20d7b9a3333ef86d70c3b3becaeccc9ef5961c41e8cd936bb1df9cf0b946c546"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "d34fe1702f55920a19bcc18f03fa4402f39635c381c30277ad358d6e82577927"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "9a4a251dbfa46f927f0fae5098abe68fdeb493dcccd553bd617ff340cbee5202"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "4ed5776aa285faad3d73e7df5ef2a35129c632ed72b167279ede5ddd488fcb4a"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dark-loading-screen.pw.toml"
hash = "389323d30065bef4d9eb2d965ce19e510bf7c9ffc64f21b6e122f2d95e1cf207"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "847dce2251028733f139692907e89466896dc6ca35cfcc1bdaa0ec1f02aebefb"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "9a386c47e3ee11b91e443d8ec1b6084eb0266b5ddbd127ea3e90c7fa4ff5d9fd"
metafile = true

[[files]]
file = "mods/e4mc.pw.toml"
hash = "e663f7a8af3dc2e071bce60131381a2ef243d9cc84ed5b74b1c2ae5cd244ac86"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "a94078a8e2634443b5b1ead28e2b2e47ab431bfe9ce3f6fc883d4a37a11cd5f6"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33d22f0f1f007754a2b13b267c395afb577616fcbb29b7473a06dca256f23803"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "b55511b63c3a96312211d26b75574d0d420035b0f30eedb40e3e12b1f42cb0a0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12fe61275734cf8d2554d5f92af20ccb22479118b36a9a56a275ad3f4b1e13fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "36587a2be418f365faa1a6deac5eadcc00b6a79ebacab25ad87839f9ddc021e7"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "12d014178cac4930a88909d241bf537c3908ff9c2c6176f2c8a22a109a4c2363"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/fluidvoidfading.pw.toml"
hash = "00d806221aaf38512d07313cb7f937b37d969961270598bf95ceb1159a36d992"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "af10334d5cb965e4255f864d8fe2c3bad90e571492bf61fd84fb55c9a9506d59"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5d6f1406628a792f100454fb8cbf3ad70a76fe58e0bdb09df3cf5e8d86e878a7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "725bcddab89e28a43bc798af763ce2844858ebfccae4e78f2d60dd6ba6194f91"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "fd344aa2c329dbb6b894ac1fcda5e82e1a965967a3dd7493b7a3e0a6eccc2226"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "6b0d890b4d8f69cabf5827e77cb3a49d99da05f854a4c251ddf2b4b7dd32e002"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "cb6164e3c3e40045becd5a12ffda6f4ce1492019add565d49656f15eb7863707"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "4aef3c4dbc01c945f4a30f63c03607aad77d16ab194983510c10ce516312e258"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "438f668eed636071ebe6ab8445d9ef37af608467c7fcdd243676b24be50360a0"
metafile = true

[[files]]
file = "mods/optiboxes.pw.toml"
hash = "b5ececca8818bf1f1ecea52efd6b3cf8f43755b5384e978b31a8f4240c1654a9"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9445550cf3fcfaaa145d60528e01c55d2fa798bcfc1232c141ddf3b94b6e0022"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "c9f156a56c3647f8003cc76e36accacf12406be6febeb35341e6f7df7a8dcaaa"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "175e1ae75e5745024f2f7da5dd359f3cef63df4f438b27ad868094c5556c652c"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "f599da7c46d2acdca321efcf35d78c53d69a73168e86344971b857bc2c754932"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "4bdb139f7f4329e080df6b9467c73391652dd85665a6a37dbce799f08baaa219"
metafile = true

[[files]]
file = "mods/server-pack-unlocker.pw.toml"
hash = "5c4d91b12d98ab2114129d24500254c0d6e6df3bab66af21367d09a4cfbdf9e5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "7c450da0da231a6e35c64fd98c395a9b7a8822ade4e42363db1b28710e0cc0d2"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "700c474b7dbb3d6cf743c4262fa01233c0c2ada4976f8cadc942606eb7afe76b"
metafile = true

[[files]]
file = "mods/timeless.pw.toml"
hash = "e15ac1f577845ed95682dfb8b25886726cbefbfd576ba9d245e6305601de07f3"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d1de6d3e889db21acd36afb754f20b6ccc8c850cb7ef839047eb440e6114d652"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dc66d444a8cfd427c3c05d47babcc43f7fca842c1d7731116bd07c7d88441edc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/chat+.pw.toml"
hash = "c02363de4ce87adbeefef2754cc1a38c37920631769d713b700c3c759d0e4fa6"
metafile = true

[[files]]
file = "resourcepacks/chat-reporting-helper.pw.toml"
hash = "b33036850e44c6a79c3995027144a1758ca16e0f46c36bc068870575e2f4fe26"
metafile = true

[[files]]
file = "resourcepacks/enhanced-faithcraft.pw.toml"
hash = "f7ebff83d26ce02fa914ad1546674e534b982c068d8b596ae5393bbcaed9db43"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "54443027f9790a0afd476a208bad68a52f05f988bf6e72095a0c3056d8fd7273"
metafile = true

[[files]]
file = "resourcepacks/food-tooltips.pw.toml"
hash = "8efd9a6f5ecab8a1329b6b0e4c6512dab34a11df09065a730a199346fe7a28e0"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "2c855e3e738015350120fc4bc04a59c56e664b751cb94145f037f1ebf67d33c5"
metafile = true

[[files]]
file = "shaderpacks/MakeUp-UltraFast-9.3e.txt"
hash = "693ad3426a9baac855c1e1bbc514eccec70cb8f197dac0132b109df85ef537b4"

[[files]]
file = "shaderpacks/makeup-ultra-fast-shaders.pw.toml"
hash = "c37f620be5f4739b191c1a5eba8b90c3acdef3162b7c9b499391c16ed23f378a"
metafile = true
