name = "GABG's XVanilla"
author = "GABG"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b2d62d0d321ba3fb81c52cff0b6468d87be417bb877c5244b566b37cee74441"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
