name = "GABG's XVanilla"
author = "GABG"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3b0f55ddb619e02512775b2b2c2227a78eecbc188c487349c713b7ec4a3b0d9"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
