name = "GABG's XVanilla"
author = "GABG"
version = "3.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3046b55fad746fc92126692b2679c8f8c02bd68cac1e4fbd9b3b3d77f75d4e4"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
